name: test
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  test_code:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.10']
      fail-fast: false

    steps:
      - name: Checkout and get LFS
        uses: actions/checkout@v3
        with:
          lfs: true

      - name: Checkout LFS objects
        run: git lfs checkout

      - name: Setup conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
          activate-environment: gphs445
          environment-file: environment.yml
          condarc-file: .github/test_condarc.yml
          auto-activate-base: false

      - name: run test suite
        shell: bash -l {0}
        run: pytest --nbval --sanitize-with doc_sanitize.cfg
