name: test
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  test_code:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.13']
      fail-fast: false

    steps:
      - name: Checkout and get LFS
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Checkout LFS objects
        run: git lfs checkout

      - name: Setup conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: ${{ matrix.python-version }}
          activate-environment: gphs445

      - name: Update env
        run: conda env update -n gphs445 -f environment.yml

      - name: Install test packages
        run: conda env update -n gphs445 -f .github/test_condarc.yml

      - name: run test suite
        shell: bash -l {0}
        run: pytest --nbval --sanitize-with doc_sanitize.cfg
